name: Build AppImage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Download pkg2appimage
        run: |
          wget https://github.com/AppImage/pkg2appimage/releases/download/continuous/pkg2appimage-x86_64.AppImage
          chmod +x pkg2appimage-x86_64.AppImage

      - name: Create FWCrypt.yml
        run: |
          cat <<EOF > FWCrypt.yml
          app: FWCrypt

          ingredients:
            dist: focal
            sources:
              - deb http://archive.ubuntu.com/ubuntu/ focal main universe
            packages:
              - ruby
          script:
            - cp -r app/* AppDir/usr/bin/
            - cp icon.png AppDir/usr/share/icons/hicolor/256x256/apps/FWCrypt.png
            - mkdir -p AppDir/usr/share/applications
            - cat <<EOL > AppDir/usr/share/applications/fwcrypt.desktop
              [Desktop Entry]
              Name=FWCrypt
              Exec=AppRun
              Icon=FWCrypt
              Type=Application
              Categories=Utility;
              EOL
            - cat <<EOL > AppDir/AppRun
              #!/bin/bash
              HERE="\$(dirname "\$(readlink -f "\${0}")")"
              export PATH="\$HERE/usr/bin:\$PATH"
              exec ruby "\$HERE/usr/bin/main.rb"
              EOL
            - chmod +x AppDir/AppRun
          EOF

      - name: Debug: List files
        run: ls -la

      - name: Debug: List AppDir contents
        run: ls -la AppDir

      - name: Debug: Check YAML file
        run: cat FWCrypt.yml

      - name: Build AppImage
        run: ./pkg2appimage-x86_64.AppImage FWCrypt.yml

      - name: Debug: List out directory contents
        run: ls -la out

      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: FWCrypt.AppImage
          path: out/*.AppImage
